config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/employer' => 'pages#employer'
  get '/employerAPI' => 'jobreels#jobreel_by_job_id'
  get '/vidtest' => 'pages#vidtest'
  get '/customplayer' => 'pages#customplayer'
  get '/step2/:id' => 'jobs#step2'
  get '/team' => 'dashboards#team'
  get '/settings' => 'dashboards#settings'
  get '/jobreelAPI/checkComps' => 'jobreels#check_comps'
  get '/addtoteamAPI' =>'dashboards#addtoteamAPI'
  post '/jobreelAPI' =>'jobreels#instant_jobreel'
  # Going to need to use nested resources so that a work history is created for a specific user

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :work_histories
  resources :educations
  resources :recommendations
  resources :videos
  resources :jobs
  resources :jobreels
  resource :dashboards, only: [:show]
  resources :applications
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :video, ImageUploader
  has_many :work_histories
  has_many :videos
  has_many :jobs
  has_many :jobreels
  has_many :educations
  has_many :recommendations
  after_create :set_defaults!

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 validates :first_name, presence: true, on: :update
 validates :last_name, presence: true, on: :update
 validates :title, presence: true, on: :update
 validates :city, presence: true, on: :update
 validates :state, presence: true, on: :update
 validates :bio, presence: true, on: :update
 validates :degree_type, presence: true, on: :update
 validates :degree_field, presence: true, on: :update

  def set_defaults!
    puts Dir.pwd
    self.first_name ||= "default_avatar"
    self.last_name ||= "Last Name"
    self.title = "Job Title"
    self.city = "City"
    self.state = "State"
    self.bio = "Your Bio"
    self.degree = "degree"
    self.degree_type = "Type of Degree"
    self.degree_field = "Degree Field"
    self.save!
    self.video = ImageUploader.new
    self.first_name ||= "First Name"
    if self.first_name == "First Name"
      img = Avatarly.generate_avatar(self.email, {size: 128})
    else
      img = Avatarly.generate_avatar(self.first_name + " " + self.last_name, {size: 128})
    end
    File.open('app/assets/images/avatar/' + self.email + '.png', 'wb') do |f|
      f.write img
    end
    self.image = Rails.root.join('app/assets/images/avatar/' + self.email + '.png').open
    self.save!
    set_default_jobreel(self)
  end

  private

  def set_default_jobreel(user)
    @defaultjr = Jobreel.new(user_id:user.id)
    @defaultjr.save!
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(current_user.id)
    if @user.nil?
      @user = User.new
    else
    end
    @avatar = display_avatar(@user)
    @video_avatar = display_video(@user)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    @user.update_attributes(user_params)
      if @user.valid?
        redirect_to user_path(@user)
      else
        render :edit, status: :unprocessable_entity
      end
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :title, :city, :state, :bio, :degree_type, :degree_field, :image, :image_id, :video)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your User Information</h1>
  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :title %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :degree_type %>
    <%= f.input :degree_field %>
    <%= f.input :bio %>
    <%= f.input :image %>
    <%= f.input :video %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<!-- User Edit Modal -->
<div class="modal fade bd-example-modal-lg" id="userModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content modal-lg">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit User Info</h4>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <%= simple_form_for @user do |f| %>
          <div class="row padded">
            <div class="col-3">
              <%= f.input :first_name %>
            </div>
            <div class="col-1">
              &nbsp;
            </div>
            <div class="col-3">
              <%= f.input :last_name %>
            </div>
            <div class="col-1">
              &nbsp;
            </div>
            <div class="col-3">
              <%= f.input :title %>
            </div>
          </div>
          <div class="row padded">
            <div class="col-3">
              <%= f.input :city %>
            </div>
            <div class="col-1">
              &nbsp;
            </div>
            <div class="col-3">
              <%= f.input :state %>
            </div>
          </div>
          <div class="row padded">
            <div class="col-3">
              <%= f.input :degree_type %>
            </div>
            <div class="col-1">
              &nbsp;
            </div>
            <div class="col-3">
              <%= f.input :degree_field %>
            </div>
          </div>
          <div class="col-12">
            <%= f.input :bio, :input_html => {:rows => 4} %>
          </div>
          <div class="row padded">
            <div class="col-12">
              Current Image:
              <%= @avatar.html_safe %>
              <%= f.input :image %>
            </div>
          </div>
          <div class="row padded">
            <div class="col-12">
              Current Video:
              <%= @video_avatar.html_safe %>
              <%= f.input :video %>
            </div>
          </div>
            <br />
            <%= f.submit 'Update', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid-profile">
    <div class="row">
    <div class="card w-35">
      <div class="video-box">
        <% if @user.video.present? %>
          <%= cl_video_tag(@user.video.public_id, controls: true, quality: 50, version: @user.video.stored_version) %>
        <% else %>
        <% end %>
      </div>
      <div class="card-block">
      <div class='booyah-box user-profile'>
        <div class ="row blue-box">
          <h1><%= @user.first_name %> <%= @user.last_name %></h1>&nbsp;&nbsp;<%= link_to link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_user_path(@user), data: {toggle: 'modal', target: '#userModal'} %>
        </div>
        <div class="row blue-box">
          <h2><%= @user.title %></h2><br />
        </div>
        <div class="row blue-box-city-degree">
          <%= image_tag 'location-icon.png' %><h3>&nbsp;&nbsp;&nbsp;<%= @user.city %>, <%= @user.state %></h3>
        </div>
        <div class="row blue-box-city-degree">
          <%= image_tag 'education-icon.png' %><h3>&nbsp;&nbsp;<%= @user.degree_type %>, <%= @user.degree_field %></h3>
        </div>
        <br />
        <div class="row blue-box">
          <h4>about</h4><br />
          <h5><%= @user.bio %></h5>
        </div>

        <div class='row badges justify-content-between'>
          <%= image_tag 'badge-1.png' %><%= image_tag 'badge-2.png' %><%= image_tag 'badge-3.png' %><%= image_tag 'badge-4.png' %>
        </div>



      </div> <!-- End user-profile -->
    </div><!-- End user-profile card block -->

    <div class="card-footer">
      <div class="logo-box text-center">
        <%= link_to image_tag('logo-new.png'), root_path %>
      </div> <!-- End logo-box -->
    </div>
  </div> <!-- End card -->


    <div class="card w-65">

      <div class="social">
        <div class="row justify-content-between">
          <button class='hire-button'>Hire <%= @user.first_name %></button>

          <div class='social-icons'>
            <%= image_tag 'facebook-icon.png' %>&nbsp;<%= image_tag 'twitter-icon.png' %>&nbsp;<%= image_tag 'linkedin-icon.png' %>&nbsp;<%= image_tag 'mail-icon.png' %>
          </div>

        </div>
      </div>

      <div class="card-block whiten">
            <div id="timeline" style="float:left; padding-left: 34px">
             <div id="timeline-bar" class="timeline-bar" style="margin-top: 0px; height: 1025px;">
               <div id="timeline-bar-inner" class="fill" style="height: 135px;"></div>
             </div>
           </div>
          <div class='booyah-box work-history'>

            <div class ="row">
              <i class="fa fa-university" aria-hidden="true"></i><h1>Education</h1>&nbsp;<%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>'.html_safe, new_education_path(@user) %>
            </div>
        <br />
        <% @user.educations.order(:college_start_date).each do |education| %>
        <div class="row justify-content-between padded2">
          <!-- This edit button should pop open a modal/live edit -->
          <h2><%= education.college_name %>&nbsp;<%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_education_path(education) %>&nbsp;<%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, education_path(education), method: :delete, data: {confirm: 'Are you sure you want to delete this?'} %></h2>
          <br \>
          <div>
            <h4><%= education.college_start_date.to_date.strftime("%B %Y") %> - <%= education.college_end_date.to_date.strftime("%B %Y") %></h4>
          </div>
        </div>
        <hr width="94%">
            <h3><p class="padded3"><%= education.college_name.upcase %><%= education.college_major.upcase %></p></h3>
          <h5><p class="padded4"><%= education.education_description %></p></h5>
          <br />
        <% end %>

            <div class ="row">
              <i class="fa fa-briefcase" aria-hidden="true"></i><h1>Work History</h1>&nbsp;<%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>'.html_safe, new_work_history_path(@user) %>
            </div>
        <br />
        <% @user.work_histories.order(:job_start_date).each do |workhistory| %>
        <div class="row justify-content-between padded2">
          <!-- This edit button should pop open a modal/live edit -->
          <h2><%= workhistory.company_name %>&nbsp;<%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_work_history_path(workhistory) %>&nbsp;<%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, work_history_path(workhistory), method: :delete, data: {confirm: 'Are you sure you want to delete this?'} %></h2>
          <br \>
          <div>
            <h4><%= workhistory.job_start_date.strftime("%B %Y") %> - <%= workhistory.job_end_date.strftime("%B %Y") %></h4>
          </div>
        </div>
        <hr width="94%">
            <h3><p class="padded3"><%= workhistory.job_title.upcase %></p></h3>
          <h5><p class="padded4"><%= workhistory.job_description %></p></h5>
          <br />
        <% end %>

        <div class ="row">
          <i class="fa fa-thumbs-o-up" aria-hidden="true"></i><h1>Recommendations</h1>&nbsp;<%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i>'.html_safe, new_recommendation_path(@user) %>
        </div>
    <br />
    <% @user.recommendations.order(:time_known).each do |recommendation| %>
    <div class="row justify-content-between padded2">
      <div>
        <h2><%= cl_image_tag(recommendation.profile_image.public_id + ".png", :width=>40, :height=>40, :gravity=>"face", :radius=>"20", :crop=>"thumb") %></h2>
        <h2><%= recommendation.company_name %>&nbsp;<%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_recommendation_path(recommendation) %>&nbsp;<%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, recommendation_path(recommendation), method: :delete, data: {confirm: 'Are you sure you want to delete this?'} %></h2>
        <h3><p class="padded3"><%= recommendation.company_title.upcase %></p></h3>
        <h5><p class="padded4"><%= recommendation.user_relationship %>, <%= recommendation.time_known %></p></h5>

      </div>

      <br \>
      <div>

      </div>
    </div>
      <br />
    <% end %>


      </div><!-- End work-history -->
      <br />
</div> <!-- End card-block -->
  </div> <!-- End card -->
</div> <!-- End row wrapper -->
</div><!-- End container wrapper -->