config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/employer' => 'pages#employer'
  get '/employerAPI' => 'jobreels#jobreel_by_job_id'
  get '/vidtest' => 'pages#vidtest'
  get '/customplayer' => 'pages#customplayer'
  get '/step2/:id' => 'jobs#step2'
  get '/team' => 'dashboards#team'
  get '/settings' => 'dashboards#settings'
  get '/jobreelAPI/checkComps' => 'jobreels#check_comps'
  get '/addtoteamAPI' =>'dashboards#addtoteamAPI'
  post '/jobreelAPI' =>'jobreels#instant_jobreel'
  # Going to need to use nested resources so that a work history is created for a specific user

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :work_histories
  resources :educations
  resources :recommendations
  resources :videos
  resources :jobs
  resources :jobreels
  resource :dashboards, only: [:show]
  resources :applications
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
before_action :authenticate_user!

  def show
    @user = current_user
    gon.user_id = @user.id
    @workhistory = WorkHistory.where(user_id: current_user.id)
    @videos = Video.where(user_id: current_user.id)
    @jobreels = Jobreel.where(user_id: current_user.id)
    @jobs = Job.where(user_id: current_user.id)
    @recs = Recommendation.where(user_id: current_user.id)

    @video_avatar = display_video(@user)
  end

  def team
    @user = current_user
    @workhistory = WorkHistory.where(user_id: current_user.id)
    @videos = Video.where(user_id: current_user.id)
    @jobreels = Jobreel.where(user_id: current_user.id)
    @jobs = Job.order(created_at: :desc).where(user_id: current_user.id)
    @recs = Recommendation.where(user_id: current_user.id)
    @teamcheck = User.all
    gon.user_id = @user.id
  end

  def settings
    @user = current_user
    @workhistory = WorkHistory.where(user_id: current_user.id)
    @videos = Video.where(user_id: current_user.id)
    @jobreels = Jobreel.where(user_id: current_user.id)
    @jobs = Job.where(user_id: current_user.id)
    @recs = Recommendation.where(user_id: current_user.id)
    gon.user_id = @user.id
  end

  def addtoteamAPI
    @userlist = User.select("id, title, image, image_id, first_name, last_name").all

    render json: @userlist
  end

  def addnewpersonAPI
    @joblist = Job.select("id, job_title, logo, city, state, created_at").all

    render json: @joblist
  end  

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/settings.html.erb
<div class="container-fluid-dashboard">
  <div class="row dashboard-bar justify-content-center">
    <div class="col-3 nopadding">
      <div class="dashboard-menu">
        <div class="row dashboard-top-box">
          <div class="dashboard-avatar-change"><%= image_tag('change-1.png', :onclick => "cloudAvatar()")%></div>
          <% if @user.image_id? %>
            <%= cl_image_tag(@user.image_id, :width => 110, :height => 110,
             :crop => :thumb, :gravity => :face, :radius => :max) %>
          <% else %>
            <%= cl_image_tag(@user.image, :width => 110, :height => 110,
               :crop => :thumb, :gravity => :face, :radius => :max) %>
          <% end %>
            <span class="vert-helper"></span>
            <div class="dashboard-top-box-text">
              <%= @user.first_name %> <%= @user.last_name %><br /><br />
              <ul>
                <li class="row"><i class="fa fa-building fa-2" aria-hidden="true"></i><%= @user.city %></li>
                <li class="row"><i class="fa fa-map-marker fa-2" aria-hidden="true"></i><%= @user.state %></li>
              </ul>
            </div>
          </div>
        <ul class="dashboard-menu-items">
          <%= link_to dashboards_path do %>
            <li class="row dashboard-menu-items"><i class="fa fa-tachometer fa-3" aria-hidden="true"></i>Dashboard</li>
          <% end %>
          <%= link_to team_path do %>
            <li class="row dashboard-menu-items"><i class="fa fa-users fa-3" aria-hidden="true"></i>Manage Team Members</li>
          <% end %>
          <%= link_to settings_path do %>
            <li class="row dashboard-menu-items dashboard-active"><i class="fa fa-cogs fa-3" aria-hidden="true"></i>Account Settings</li>
          <% end %>
          <%= link_to new_job_path do %>
            <li class="row dashboard-menu-items-bold justify-content-center">
            <i class="fa fa-plus fa-3" aria-hidden="true"></i>
            Start Job Posting
          </li>
          <% end %>
        </ul>
      </div>
      <div class="jobposting-divider">&nbsp;</div>
    </div>

    <div class="col-9 nopadding">
      <div class="dashboard-box">
        <div class="dashboard-settings">
          <div class="dashboard-settings-title">Change Email</div>
          <div class="dashboard-settings-form">
            <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, id: "email-update-form" }, :format => :json, :remote => true ) do |f| %>

              <div class="dashboard-settings-form-content">
                 <%= f.input :email_placeholder, id: "current-email", required: false, class: "form-control", placeholder: "Email Address", input_html: {value: @user.email}, label: "Current Email Address", autocomplete: false, disabled: true %>           
              </div>

              <div class="dashboard-settings-form-content">
                 <%= f.input :email, id: "new-email", required: true, class: "form-control", placeholder: "Email address", input_html: {value: @user.email}, label: "New Email Address", autocomplete: false %>  
              </div>

              <div class="dashboard-settings-form-content">
                <%= f.input :current_password, required: true, class: "form-control", id: "", value: "", placeholder: "Enter your password", autocomplete: false %>
              </div>
              <%= f.button :submit, "Update", disabled: true, :id => "email-update-button", :class => "btn-settings" %>
            <% end %>
          </div>
        </div>
      </div><br />

      <div class="dashboard-box">
        <div class="dashboard-settings">
          <div class="dashboard-settings-title">Change Password</div>
          <div class="dashboard-settings-form">
            <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, id: "password-update-form" }, :format => :json, :remote => true ) do |f| %>

              <div class="dashboard-settings-form-content">
                 <%= f.input :current_password, id: "", required: true, class: "form-control", placeholder: "Enter your existing password", label: "Old Password", autocomplete: false %>           
              </div>

              <div class="dashboard-settings-form-content">
                 <%= f.input :password, id: "", required: true, class: "form-control", placeholder: "Enter your new password", label: "New Password", autocomplete: false %>       
              </div>

              <div class="dashboard-settings-form-content">
                <%= f.input :password_confirmation, required: true, class: "form-control", id: "", value: "", placeholder: "Retype your new password", label: "Retype Password", autocomplete: false %>
              </div>
              <%= f.button :submit, "Update", disabled: true, :id => "password-update-button", :class => "btn-settings" %>
            <% end %>
          </div>
        </div>
      </div><br /><br /><br /><br />
    </div>    

  </div>
</div>

app/views/dashboards/show.html.erb
<div class="container-fluid-dashboard">
  <div class="row dashboard-bar justify-content-center">
    <div class="col-3 nopadding">
      <div class="dashboard-menu">
        <div class="row dashboard-top-box">
          <div class="dashboard-avatar-change"><%= image_tag('change-1.png', :onclick => "cloudAvatar()")%></div>
          <% if @user.image_id? %>
            <%= cl_image_tag(@user.image_id, :width => 110, :height => 110,
             :crop => :thumb, :gravity => :face, :radius => :max) %>
          <% else %>
            <%= cl_image_tag(@user.image, :width => 110, :height => 110,
               :crop => :thumb, :gravity => :face, :radius => :max) %>
          <% end %>
            <span class="vert-helper"></span>
            <div class="dashboard-top-box-text">
              <%= @user.first_name %> <%= @user.last_name %><br /><br />
              <ul>
                <li class="row"><i class="fa fa-building fa-2" aria-hidden="true"></i><%= @user.city %></li>
                <li class="row"><i class="fa fa-map-marker fa-2" aria-hidden="true"></i><%= @user.state %></li>
              </ul>
            </div>
          </div>
        <ul class="dashboard-menu-items">
          <%= link_to dashboards_path do %>
            <li class="row dashboard-menu-items dashboard-active"><i class="fa fa-tachometer fa-3" aria-hidden="true"></i>Dashboard</li>
          <% end %>
          <%= link_to team_path do %>
            <li class="row dashboard-menu-items"><i class="fa fa-users fa-3" aria-hidden="true"></i>Manage Team Members</li>
          <% end %>
          <%= link_to settings_path do %>
            <li class="row dashboard-menu-items"><i class="fa fa-cogs fa-3" aria-hidden="true"></i>Account Settings</li>
          <% end %>
          <%= link_to new_job_path do %>
            <li class="row dashboard-menu-items-bold justify-content-center">
            <i class="fa fa-plus fa-3" aria-hidden="true"></i>
            Start Job Posting
          </li>
          <% end %>
        </ul>
      </div>
      <div class="jobposting-divider">&nbsp;</div>
    </div>

    <div class="col-9 nopadding">
      <div class="dashboard-box">
        <div class="row dashboard-title nomargin">
          <div class="col-6 dashboard-title-active-job">
            <span>Active Jobs (<%= @jobs.count %>)</span>
          </div>
          <div class="col-6 dashboard-title-performance-trend">
            <span>Performance Trends</span>
          </div>
        </div>


        <% @jobs.each do |job| %>
          <div class="row nomargin dashboard-edit-icons">
            <div class="col-1 dashboard-top">
              <%= image_tag 'adobe-logo.gif' %>
            </div>
            <div class="col-4 dashboard-sidebar">
              <span><h3><%= link_to job.job_title, job_path(job) %></h3></span><br />
              <span><i class="fa fa-map-marker" aria-hidden="true"></i> <%= job.city %>, <%= job.state %></span>
            </div>
            <div class="col-1">
              <span class="vert-helper"></span>
              <%= link_to job_path(job), method: :delete, data: {confirm: 'Are you sure you want to delete this?'} do %>
                <i class="fa fa-trash-o" aria-hidden="true"></i>&nbsp
              <% end %>
              <%= link_to edit_job_path(job) do %>
                <i class="fa fa-pencil" aria-hidden="true"></i>&nbsp
              <% end %>
            </div>
            <div class="col-6 dashboard-team-avatar text-center">
              <% if @user.image_id? %>
              <%= cl_image_tag(@user.image_id, :width => 40, :height => 40,
                 :crop => :thumb, :gravity => :face, :radius => :max) %>
              <% else %>
                <%= cl_image_tag(@user.image, :width => 40, :height => 40,
                   :crop => :thumb, :gravity => :face, :radius => :max) %>
              <% end %>
                 <i class="fa fa-plus" aria-hidden="true"></i>

            </div>
          </div>
          <div class="dashboard-divider">&nbsp;</div>
          <div class="performance-trends-text">Recent Activity</div>


        <% end %>
      </div>
    </div>
  </div>
</div><br /><br /><br /><br />

app/views/dashboards/team.html.erb
<div class="container-fluid-dashboard">
  <div class="row dashboard-bar justify-content-center">
    <div class="col-3 nopadding">
      <div class="dashboard-menu">
        <div class="row dashboard-top-box">
          <div class="dashboard-avatar-change"><%= image_tag('change-1.png', :onclick => "cloudAvatar()")%>
          </div>
          <% if @user.image_id? %>
            <%= cl_image_tag(@user.image_id, :width => 110, :height => 110,
             :crop => :thumb, :gravity => :face, :radius => :max) %>
          <% else %>
            <%= cl_image_tag(@user.image, :width => 110, :height => 110,
               :crop => :thumb, :gravity => :face, :radius => :max) %>
          <% end %>
          <span class="vert-helper"></span>
          <div class="dashboard-top-box-text">
            <%= @user.first_name %> <%= @user.last_name %><br /><br />
            <ul>
              <li class="row"><i class="fa fa-building fa-2" aria-hidden="true"></i><%= @user.city %></li>
              <li class="row"><i class="fa fa-map-marker fa-2" aria-hidden="true"></i><%= @user.state %></li>
            </ul>
          </div>
        </div>
        <ul class="dashboard-menu-items">
          <%= link_to dashboards_path do %>
            <li class="row dashboard-menu-items"><i class="fa fa-tachometer fa-3" aria-hidden="true"></i>Dashboard</li>
          <% end %>
          <%= link_to team_path do %>
            <li class="row dashboard-menu-items dashboard-active"><i class="fa fa-users fa-3" aria-hidden="true"></i>Manage Team Members</li>
          <% end %>
          <%= link_to settings_path do %>
            <li class="row dashboard-menu-items"><i class="fa fa-cogs fa-3" aria-hidden="true"></i>Account Settings</li>
          <% end %>
          <%= link_to new_job_path do %>
            <li class="row dashboard-menu-items-bold justify-content-center">
            <i class="fa fa-plus fa-3" aria-hidden="true"></i>
            Start Job Posting
          </li>
          <% end %>
        </ul>
      </div>
      <div class="jobposting-divider">&nbsp;</div>
    </div>

    <div class="col-9 nopadding">
      <div class="row dashboard-title nomargin">
        <div class="col-6 team-title-active" id="team-title-active" disabled="disabled">
          <span>Active Teams (<%= @jobs.count %>)</span>
        </div>
        <div class="col-6 team-title-inactive" id="team-title-inactive">
          <span>Team Members (#?)</span>
        </div>
      </div>      
      <div class="show" id="show">
        <div class="dashboard-box">
          <% @jobs.each do |job| %>
            <div class="row nomargin team-main-row">
              <div class="col-1 team-image">
                <% if @user.image_id? %>
                  <%= cl_image_tag(@user.image_id, :width => 60, :height => 60, :crop => :thumb) %>
                <% else %>
                  <%= cl_image_tag(@user.image, :width => 60, :height => 60, :crop => :thumb) %>
                <% end %>
              </div>
              <div class="col-4 team-title-main team-title">
                <h3><%= link_to job.job_title, job_path(job) %></h3>
                <div><i class="fa fa-map-marker team-title-icon" aria-hidden="true"></i><h4><%= job.city %>, <%= job.state %></h4></div>
              </div>
              <div class="col-3 team-title-main team-title">
                <h3>Published:</h3>
                <h4>February 11th, 2017</h4>
              </div>
              <div class="col-4 team-button-spacing text-center">
                <button class="btn-team" id="addToTeam" data-jobID='<%= job.id %>' data-teamIDs='<%= job.team_ids.flatten %>'>Add New Person</button>
              </div>
            </div>  
            <div class="team-divider">&nbsp;</div>    
          
            <div class="row nomargin team-background" data-teamids="<%= job.team_ids %>" data-jobid="<%= job.id %>">
              <% job.team_ids.each do |teammember| %>
                <% @teamcheck.each do |checking| %>
                  <% if teammember == checking.id %>
                    <div class="col-1 team-avatar-image vert-align">
                      <% if checking.image_id? %>
                        <%= cl_image_tag(checking.image_id, :width => 50, :height => 50, :crop => :thumb, :gravity => :face, :radius => :max) %>
                      <% else %>
                        <%= cl_image_tag(checking.image, :width => 50, :height => 50, :crop => :thumb, :gravity => :face, :radius => :max) %>
                      <% end %>
                    </div>
                    <div class="col-2 team-title-sub team-title-sub">
                      <h3><%= checking.first_name %></h3>
                      <h4><%= checking.title %></h4>
                    </div>
                    <div class="col-1 team-icon-sub">
                      <i class="fa fa-trash-o team-trash" id="trash" data-userid="<%= checking.id %>" aria-hidden="true"></i>&nbsp         
                    </div>                    
                  <% end %>
                <% end %>                  
              <% end %>
              <div class="team-divider">&nbsp;</div>
            </div>
          <% end %>    
        </div><br />

        <div class="dashboard-box">
          <div class="dashboard-settings">
            <div class="dashboard-settings-title">Pending Team Invites</div>
            <div class="row nomargin">
              <div class="col-2 team-title-main team-title text-center vert-align">
                <h3>Nancy Moreno</h3>
              </div>
              <div class="col-3 team-title-main team-title">
                <h3>Invited:</h3>
                <h4>February 11th, 2017</h4>
              </div>
              <div class="col-3 team-title-main team-title">
                <h3>Email:</h3>
                <h4>go@myjobreel.com</h4>
              </div>
              <div class="col-1 team-image-pending">
                <% if @user.image_id? %>
                  <%= cl_image_tag(@user.image_id, :width => 60, :height => 60, :crop => :thumb) %>
                <% else %>
                  <%= cl_image_tag(@user.image, :width => 60, :height => 60, :crop => :thumb) %>
                <% end %>
              </div>
              <div class="col-3 team-title-main team-title vert-align">
                <h3>Senior Engineer</h3>
              </div>            
              <div class="col-1 team-icon-sub-sub text-center">
                <i class="fa fa-repeat" aria-hidden="true"></i>
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              </div>
            </div>
            <div class="team-divider">&nbsp;</div> 
            <div class="row nomargin">
              <div class="col-2 team-title-main team-title text-center vert-align">
                <h3>Nancy Moreno</h3>
              </div>
              <div class="col-3 team-title-main team-title">
                <h3>Invited:</h3>
                <h4>February 11th, 2017</h4>
              </div>
              <div class="col-3 team-title-main team-title">
                <h3>Email:</h3>
                <h4>go@myjobreel.com</h4>
              </div>
              <div class="col-1 team-image-pending">
                <% if @user.image_id? %>
                  <%= cl_image_tag(@user.image_id, :width => 60, :height => 60, :crop => :thumb) %>
                <% else %>
                  <%= cl_image_tag(@user.image, :width => 60, :height => 60, :crop => :thumb) %>
                <% end %>
              </div>
              <div class="col-3 team-title-main team-title vert-align">
                <h3>Senior Engineer</h3>
              </div>            
              <div class="col-1 team-icon-sub-sub text-center">
                <i class="fa fa-repeat" aria-hidden="true"></i>
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              </div>
            </div>        
          </div>
        </div><br />
      </div>
<!-- End active view -->
      <div class="hidden" id="hidden">
        <div class="dashboard-box">
          <div class="row nomargin team-main-row">
            <div class="col-1 team-image">
              <% if @user.image_id? %>
                <%= cl_image_tag(@user.image_id, :width => 60, :height => 60, :crop => :thumb) %>
              <% else %>
                <%= cl_image_tag(@user.image, :width => 60, :height => 60, :crop => :thumb) %>
              <% end %>
            </div>
            <div class="col-4 team-title-main team-title">
              <h3>Nancy Moreno</h3>
              <h4>Manager</h4>
            </div>
            <div class="col-3 team-title-main team-title">
              <h3>Joined:</h3>
              <h4>February 11th, 2017</h4>
            </div>
            <div class="col-4 team-button-spacing text-center">
              <button class="btn-add-team">Add To Team</button>
            </div>
          </div>
          <div class="team-divider">&nbsp;</div>     
      </div><br />

      <div class="dashboard-box">
        <div class="dashboard-settings">
          <div class="dashboard-settings-title">Pending Team Invites</div>
          <div class="row nomargin">
            <div class="col-2 team-title-main team-title text-center vert-align">
              <h3>Nancy Moreno</h3>
            </div>
            <div class="col-3 team-title-main team-title">
              <h3>Invited:</h3>
              <h4>February 11th, 2017</h4>
            </div>
            <div class="col-3 team-title-main team-title">
              <h3>Email:</h3>
              <h4>go@myjobreel.com</h4>
            </div>
            <div class="col-1 team-image-pending">
              <% if @user.image_id? %>
                <%= cl_image_tag(@user.image_id, :width => 60, :height => 60, :crop => :thumb) %>
              <% else %>
                <%= cl_image_tag(@user.image, :width => 60, :height => 60, :crop => :thumb) %>
              <% end %>
            </div>
            <div class="col-3 team-title-main team-title vert-align">
              <h3>Senior Engineer</h3>
            </div>            
            <div class="col-1 team-icon-sub-sub text-center">
              <i class="fa fa-repeat" aria-hidden="true"></i>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            </div>
          </div>
          <div class="team-divider">&nbsp;</div> 
          <div class="row nomargin">
            <div class="col-2 team-title-main team-title text-center vert-align">
              <h3>Nancy Moreno</h3>
            </div>
            <div class="col-3 team-title-main team-title">
              <h3>Invited:</h3>
              <h4>February 11th, 2017</h4>
            </div>
            <div class="col-3 team-title-main team-title">
              <h3>Email:</h3>
              <h4>go@myjobreel.com</h4>
            </div>
            <div class="col-1 team-image-pending">
              <% if @user.image_id? %>
                <%= cl_image_tag(@user.image_id, :width => 60, :height => 60, :crop => :thumb) %>
              <% else %>
                <%= cl_image_tag(@user.image, :width => 60, :height => 60, :crop => :thumb) %>
              <% end %>
            </div>
            <div class="col-3 team-title-main team-title vert-align">
              <h3>Senior Engineer</h3>
            </div>            
            <div class="col-1 team-icon-sub-sub text-center">
              <i class="fa fa-repeat" aria-hidden="true"></i>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            </div>
          </div>        
        </div>
      </div><br />
    </div>
<!-- End inactive view -->    
  </div>
</div><br /><br /><br /><br />