config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/employer' => 'pages#employer'
  get '/employerAPI' => 'jobreels#jobreel_by_job_id'
  get '/vidtest' => 'pages#vidtest'
  get '/customplayer' => 'pages#customplayer'
  get '/step2/:id' => 'jobs#step2'
  get '/team' => 'dashboards#team'
  get '/settings' => 'dashboards#settings'
  get '/jobreelAPI/checkComps' => 'jobreels#check_comps'
  get '/addtoteamAPI' =>'dashboards#addtoteamAPI'
  post '/jobreelAPI' =>'jobreels#instant_jobreel'
  # Going to need to use nested resources so that a work history is created for a specific user

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :work_histories
  resources :educations
  resources :recommendations
  resources :videos
  resources :jobs
  resources :jobreels
  resource :dashboards, only: [:show]
  resources :applications
end

app/models/application.rb
class Application < ApplicationRecord
# has_many :comments
# has_many :ratings

belongs_to :user


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competency.rb
class Competency < ApplicationRecord
  has_many :questions

  belongs_to :job, optional: true
  belongs_to :jobreel, optional: true
  
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user

  validates :college_major, presence: true
  validates :college_name, presence: true
  validates :college_end_date, presence: true
  validates :education_description, presence: true
  validates :college_start_date, presence: true

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user

  has_many :jobreels
  has_many :videos
  has_many :competencies
  has_many :questions
  
  validates_uniqueness_of :job_title, scope: [:user_id, :city, :state]
  after_create :create_jobreel_for_job!


  def create_jobreel_for_job!
    @jobreel = Jobreel.new()
    @jobreel.user_id = Job.last.user_id
    @jobreel.job_id = Job.last.id
    @jobreel.section1_title = "About the Company"
    @jobreel.section2_title = "Challenges"
    @jobreel.section3_title = "Expectations"
    @jobreel.section4_title = "Team"
    @jobreel.section5_title = "Perks & Benefits"
    @jobreel.section1_duration = 0
    @jobreel.section2_duration = 0
    @jobreel.section3_duration = 0
    @jobreel.section4_duration = 0
    @jobreel.section5_duration = 0
    @jobreel.save!
  end

end

app/models/jobreel.rb
class Jobreel < ApplicationRecord
  belongs_to :user
  belongs_to :job, optional: true

  has_many :videos
  has_many :competencies
  has_many :questions

  def job_title
    job ? job.job_title : "Profile Jobreel"
  end

  def as_json(options = { })
    h = super (options)
    h[:job_title] = job_title
    h
  end

  def get_section1_videos
    JSON.parse(section1_videos)
  end

  def get_videos(section)
    JSON.parse(section)
    case section
    when :section1
      JSON.parse(section1_videos)
    when :section2
      JSON.parse(section2_videos)
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :competency
  belongs_to :jobreel, optional: true
  belongs_to :job, optional: true

  validates :text, presence: true
  validates :competency_id, presence: true

end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  mount_uploader :profile_image, RecommendationUploader

  belongs_to :user

  validates :company_title, presence: true
  validates :company_name, presence: true
  validates :time_known, presence: true
  validates :user_relationship, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :video, ImageUploader
  has_many :work_histories
  has_many :videos
  has_many :jobs
  has_many :jobreels
  has_many :educations
  has_many :recommendations
  after_create :set_defaults!

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 validates :first_name, presence: true, on: :update
 validates :last_name, presence: true, on: :update
 validates :title, presence: true, on: :update
 validates :city, presence: true, on: :update
 validates :state, presence: true, on: :update
 validates :bio, presence: true, on: :update
 validates :degree_type, presence: true, on: :update
 validates :degree_field, presence: true, on: :update

  def set_defaults!
    puts Dir.pwd
    self.first_name ||= "default_avatar"
    self.last_name ||= "Last Name"
    self.title = "Job Title"
    self.city = "City"
    self.state = "State"
    self.bio = "Your Bio"
    self.degree = "degree"
    self.degree_type = "Type of Degree"
    self.degree_field = "Degree Field"
    self.save!
    self.video = ImageUploader.new
    self.first_name ||= "First Name"
    if self.first_name == "First Name"
      img = Avatarly.generate_avatar(self.email, {size: 128})
    else
      img = Avatarly.generate_avatar(self.first_name + " " + self.last_name, {size: 128})
    end
    File.open('app/assets/images/avatar/' + self.email + '.png', 'wb') do |f|
      f.write img
    end
    self.image = Rails.root.join('app/assets/images/avatar/' + self.email + '.png').open
    self.save!
    set_default_jobreel(self)
  end

  private

  def set_default_jobreel(user)
    @defaultjr = Jobreel.new(user_id:user.id)
    @defaultjr.save!
  end


end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :cloud_video, VideoUploader
  belongs_to :user
  belongs_to :job, optional: true
  belongs_to :work_history, optional: true
  belongs_to :jobreel, optional: true


end

app/models/work_history.rb
class WorkHistory < ActiveRecord::Base
  belongs_to :user
  has_many :videos

  validates :job_title, presence: true
  validates :company_name, presence: true
  validates :job_end_date, presence: true
  validates :job_description, presence: true
  validates :job_start_date, presence: true
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/jobreels_helper.rb
module JobreelsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def default_intro(video)
    return cl_video_tag("default_intro", controls: true) if video.nil?
    cl_video_tag(video.private_id, controls: true, transformation: @overlays)
  end

  def jobreel_default_intro(video)

    return cl_video_tag("default_intro", controls: true) if video.nil?
    jsonvideo = JSON.parse(video)
    ev = []
    firstvid = jsonvideo.shift
    jsonvideo.each do |vid|
      ev << {:overlay=>"video:" + vid, :flags=>"splice", :width=>333, :height=>188, :crop=>"fill"}
    end
    overlays = [{:width=>333, :height=>188, :crop=>"fill"}]
    overlays << ev
    overlays.flatten!
    cl_video_tag(firstvid, controls: true, transformation: overlays)
  end

end

app/views/layouts/_employer-index-navbar.html.erb
<!-- Show on the employer signin/up page -->

  <nav class="navbar navbar-toggleable-md">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to (image_tag ("logo-new.png"), class: 'nav-image'), root_path %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <% end %>
          <li class="nav-item">
            <%= link_to 'For Job Seekers', root_path, class: 'nav-link' %>
          </li>
      </ul>
    </div>
  </nav>
  <script>
$(document).on('turbolinks:load', function(){
    $("form#login-box").bind ("ajax:success", function(e, data, status, xhr){
     if (data.success) {
      //javascript that executes if everything goes o.k.
      $('#signinModal').modal('hide');
      window.location.replace("http://localhost:3030/dashboards/");
      location.reload();
    }
     else {
      alert('failure!');
    }
    );
    $("form#signup-box").bind ("ajax:success", function(e, data, status, xhr){
      console.log(e);
      console.log(data);
      console.log(status);
     if (data.success)
      //javascript that executes if everything goes o.k.
      $('#signupModal').modal('hide');
      window.location.replace("http://localhost:3030/dashboards/");
     else {
      alert('failure!');
    }
    );
  });
  </script>

app/views/layouts/_footer.html.erb
<!-- use https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/ -->
  <!-- Universal page footer -->
  <footer class="footer-private-view">
    <div class="container-fluid-footer-private">
      <div class="row footer-flex">

        <div class="footer-logo-box col-2 vert-align">
          <%= link_to (image_tag ("logo-new.png"), class: 'nav-image'), root_path %>
          <span class = "footer-logo-text">© 2017 JobReel, Inc.<br>
          All rights reserved.</span>
        </div>

        <div class="verticalLine "></div>

        <div class="list-footer-left col-2">
          <nav>
            <ul style="list-style-type: none">
              <li><a href="#">Dashboard</a>
              </li>
              <li><a href="#">Explore</a>
              </li>
              <li><a href="#">My Network</a>
              </li>
              <li><a href="#">My Jobs</a>
              </li>
              <li><a href="#">Support</a>
              </li>
            </ul>
          </nav>
        </div>

        <div class="list-footer-middle col-2">
          <nav>
            <ul style="list-style-type: none">
              <li><a href="#">About</a>
              </li>
              <li><a href="#">Contact</a>
              </li>
              <li><a href="#">Terms of Service</a>
              </li>
              <li><a href="#">Privacy Policy</a>
              </li>
            </ul>
          </nav>
        </div>

        <div class="verticalLine"></div>

        <div class="social-footer col-2">
          <h1>Follow Us</h1>
          <div class="row social-footer-list" id="footer-facebook">
            <%= image_tag 'facebook-footer-icon.png' %><h3>&nbsp&nbsp&nbsp&nbsp<a href="#">Facebook</a></h3>
          </div>
          <div class="row social-footer-list" id="footer-twitter">
            <%= image_tag 'twitter-footer-icon.png' %><h3>&nbsp&nbsp&nbsp<a href="#">Twitter</a></h3>
          </div>
          <div class="row social-footer-list" id="footer-rss">
            <%= image_tag 'rss-icon.png' %><h3>&nbsp&nbsp&nbsp&nbsp<a href="#">RSS</a></h3>
          </div>
        </div>

        <div class="verticalLine"></div>

        <div class="newsletter-footer col-4">
          <h1>Subscribe To Our News</h1>
          <div class="row newsletter-bar-footer ">
            <input type="text" name="search" placeholder="Enter Your Email" class="newsletter-bar">
            <%= image_tag 'mail-footer-icon-green.png' %>
          </div>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_index-footer.html.erb
<!-- use https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/ -->
<span class="index-footer">
  <p>Copyrighted 2016 JobReel. All Rights Reserved.</p>
  <a href="#"><img class="opacity50" src="assets/facebook_icon.png" alt="jobreel facebook"></a>
  <a href="#"><img class="opacity50" src="assets/twitter_icon.png" alt="jobreel twitter"></a>
  <a href="#"><img class="opacity50" src="assets/instagram_icon.png" alt="jobreel instagram"></a>
  <a href="#"><img class="opacity50" src="assets/linkedin_icon.png" alt="jobreel linkedin"></a>
</span>

app/views/layouts/_index-navbar.html.erb
  <nav class="navbar navbar-toggleable-md">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to (image_tag ("logo-new.png"), class: 'nav-image'), root_path %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'For Employers', employer_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>

app/views/layouts/_navbar.html.erb
<!-- Show on all pages except user profile -->
<div class = "container-fluid-navbar">
  <div class = "navbar-body">
    <nav class="navbar navbar-toggleable-md">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to (image_tag ("logo-new.png"), class: 'nav-image'), root_path %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        </ul>
        <div class="vert-align">
        <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Jobs', jobs_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Video', video_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>
          </div>
            <%= link_to (image_tag ("notification-bell.png"), class: 'nav-image'), root_path %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if @user.image_id? %>
                <%= cl_image_tag(@user.image_id, :width => 35, :height => 35,
                   :crop => :thumb, :gravity => :face, :radius => :max) %>
                <% else %>
                  <%= cl_image_tag(@user.image, :width => 35, :height => 35,
                     :crop => :thumb, :gravity => :face, :radius => :max) %>
                <% end %>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to user_path(current_user), action: 'show', class: "no-show" do %>
              <div class="dropdown-item dd-profile text-center">
                <% if @user.image_id? %>
                <%= cl_image_tag(@user.image_id, :width => 50, :height => 50,
                   :crop => :thumb, :gravity => :face, :radius => :max) %>
                <% else %>
                  <%= cl_image_tag(@user.image, :width => 50, :height => 50,
                     :crop => :thumb, :gravity => :face, :radius => :max) %>
                <% end %>
                <span class="dd-text"><%= current_user.first_name %>&nbsp<%= current_user.last_name %></span>
                <br />
                <span class="dd-link">View/Update Profile</span>
                <% end %>
              </div>
              <a class="dropdown-item" href="#">Settings</a>
              <a class="dropdown-item" href="#">Help Center</a>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/_profile-footer.html.erb
<!-- Profile page footer -->
  <footer class="footer-public-view text-center">
    <div class="container">
      <span class="public-footer">Show off your online resume at <%= link_to 'jobreel.com', root_path %>. Already have an account? <%= link_to 'Login', root_path %>.</span>
      <br />
      <span class="public-footer-copy">COPYRIGHTED 2017 JOBREEL.COM. ALL RIGHTS RESERVED.</span>
    </div>
  </footer>

app/views/layouts/_whmodal.html.erb
<!-- Work History Edit Modal -->
<div class="modal fade bd-example-modal-lg" id="whModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Job Info</h4>
      </div>
        <div class="modal-body">
          <div class="container-fluid">
          <%= simple_form_for @test do |f| %>
          <div class="row padded">
            <div class="col-5">
            <%= f.input :company_name %>
          </div>
            <div class="col-1">&nbsp</div>
            <div class="col-5">
            <%= f.input :job_title %>
          </div>
          </div>
            <div class="row padded">
              <div class="col-5">
              <%= f.input :job_start_date %>
              </div>
              <div class="col-1">&nbsp</div>
              <div class="col-5">
              <%= f.input :job_end_date %>
              </div>
          </div>
          <div class="col-12">
            <%= f.input :job_description, :input_html => {:rows => 4} %>
          </div>
            <br />
            <%= f.submit 'Update', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <title>Product</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name%>-<%= controller.action_name%>">
    <header class="Site-header">
      <!-- from http://stackoverflow.com/questions/19036541/in-rails-4-how-can-i-change-the-text-in-the-nav-bar-based-on-the-current-page -->
      <% if ((params[:action] == 'index') && (params[:controller] == 'pages')) %>
        <%= render "layouts/index-navbar" %>
      <% end %>
      <% if params[:action] == 'employer' %>
        <%= render "layouts/employer-index-navbar" %>
      <% end %>
      <% if params[:controller] == 'dashboards' %>
        <%= render "layouts/navbar" %>
      <% end %>
      <% if params[:controller] == 'jobs' %>
        <%= render "layouts/navbar" %>
      <% end %>
      <% if params[:controller] == 'videos' %>
        <%= render "layouts/navbar" %>
      <% end %>
      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </header>

    <main class="Site-content">
      <%= yield %>
    </main>

    <footer class="Site-footer">
      <% if params[:controller] == 'users' && params[:action] == 'show' %>
        <%= render "layouts/profile-footer" %>
      <% elsif params[:controller] == 'jobs' && params[:action] == 'show' %>
        <%= render "layouts/footer" %>
      <% elsif params[:controller] == 'dashboards' %>
        <%= render "layouts/footer" %>
      <% elsif !user_signed_in? %>
        <%= render "layouts/index-footer" %>
      <% else %>
      <% end %>
    </footer>

  </body>
</html>

app/views/pages/employer.html.erb
<div class="container-fluid-index">
  <div class="cta-box">
    <div class="col-12 logo vert-align">
      <p><span class="big-blue">job</span>reel</p>
    </div>
    <br />
    <div class = "row welcome-box">
      <div class="col-6 login-tab-active vert-align" id="login-tab">
        LOG IN
      </div>
      <div class="col-6 signup-tab-inactive vert-align" id="signup-tab">
        SIGN UP
      </div>
      <div class="col-12 welcome-bar vert-align" id="welcome-bar">
        <br />
        <span class="big-blue">WELCOME BACK EMPLOYER!</span>
        <br />
      </div>
      <div class="col-12 login-form-box" id="login-form-box">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {:id => "login-box"},:format => :json, :remote => true) do |f| %>
        <div class="form-inputs">
          <%= f.email_field :email, required: false, placeholder: "Email", autofocus: true %>
          <br />
          <br />
          <%= f.password_field :password, required: false, placeholder: "Password" %>
          <br /><br />
        </div>
        <div class="loginbox-rememberme">
          <%= f.label :remember_me do %>
            <%= f.check_box :remember_me %>
            <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
              Remember me<%= link_to "Forgot your password?", new_password_path(resource_name), {:style=>'margin-left: 150px;'} %><br />
            <% end %>
          <% end %>
        </div>
        <br />
        <div class="form-actions">
          <%= f.submit "EMPLOYER LOG IN", :class => "btn btn-info btn-block" %>
        </div>
        <% end %>
        <br />
        <div class="loginbox-links text-center">
          No account? <span id="signup-tab-text"> Sign up now!</span><br />
        </div>
      </div>
      <div class="col-12 signup-form-box" id="signup-form-box">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), :html => {:id => "signup-box"},:format => :json, :remote => true) do |f| %>
        <div class="form-inputs">
          <%= f.text_field :first_name, required: true, placeholder: "First Name", autofocus: true %>
          <br />          <br />
          <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
          <br />          <br />
          <%= f.email_field :email, required: true, placeholder: "Email" %>
          <br />          <br />
          <%= f.password_field :password, required: true, placeholder: "Password" %>
          <br />          <br />
          <%= f.password_field :password_confirmation, required: true, placeholder: "Confirm Password" %>
          <%= f.hidden_field :employer_role, value: true %>
        </div>
        <br />
        <div class="form-actions">
          <%= f.submit "EMPLOYER SIGN UP", :class => "btn btn-info btn-block" %>
        </div>
        <% end %>
        <br />
        <div class="loginbox-links text-center">
          Already have an account? <span id="login-tab-text"> Log in now!</span><br />
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container-fluid-index">
  <div class="cta-box">
    <div class="col-12 logo vert-align">
      <p><span class="big-blue">job</span>reel</p>
    </div>
    <br />
    <div class = "row welcome-box">
      <div class="col-6 login-tab-active vert-align" id="login-tab">
        LOG IN
      </div>
      <div class="col-6 signup-tab-inactive vert-align" id="signup-tab">
        SIGN UP
      </div>
      <div class="col-12 welcome-bar vert-align" id="welcome-bar">
        <br />
        <span class="big-blue">WELCOME BACK JOB SEEKER!</span>
        <br />
      </div>
      <div class="col-12 login-form-box" id="login-form-box">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {:id => "login-box"},:format => :json, :remote => true) do |f| %>
        <div class="form-inputs">
          <%= f.email_field :email, required: false, placeholder: "Email", autofocus: true %>
          <br />
          <br />
          <%= f.password_field :password, required: false, placeholder: "Password" %>
          <br /><br />
        </div>
        <div class="loginbox-rememberme">
          <%= f.label :remember_me do %>
            <%= f.check_box :remember_me %>
            <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
              Remember me<%= link_to "Forgot your password?", new_password_path(resource_name), {:style=>'margin-left: 150px;'} %><br />
            <% end %>
          <% end %>
        </div>
        <br />
        <div class="form-actions">
          <%= f.submit "JOB SEEKER LOG IN", :class => "btn btn-info btn-block" %>
        </div>
        <% end %>
        <br />
        <div class="loginbox-links text-center">
          No account? <span id="signup-tab-text"> Sign up now!</span><br />
        </div>
      </div>
      <div class="col-12 signup-form-box" id="signup-form-box">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), :html => {:id => "signup-box"},:format => :json, :remote => true) do |f| %>
        <div class="form-inputs">
          <%= f.text_field :first_name, required: true, placeholder: "First Name", autofocus: true %>
          <br />          <br />
          <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
          <br />          <br />
          <%= f.email_field :email, required: true, placeholder: "Email" %>
          <br />          <br />
          <%= f.password_field :password, required: true, placeholder: "Password" %>
          <br />          <br />
          <%= f.password_field :password_confirmation, required: true, placeholder: "Confirm Password" %>
        </div>
        <br />
        <div class="form-actions">
          <%= f.submit "JOB SEEKER SIGN UP", :class => "btn btn-info btn-block" %>
        </div>
        <% end %>
        <br />
        <div class="loginbox-links text-center">
          Already have an account? <span id="login-tab-text"> Log in now!</span><br />
        </div>
      </div>
    </div>
  </div>
</div>